### ISSUE TITLE
Settings - Scope may cause null reference exception

### ISSUE THREAD

**Issue by rolandoldengarm** [rjygraham/Ng4AspNetCore.StarterWeb#5]
Hi great repo! Just setting things up.

Found that after you set up the app, and run it, it throws a null ref exception at this line: https://github.com/rjygraham/Ng4AspNetCore.StarterWeb/blob/master/Ng4AspNetCore.StarterWeb/Settings/AzureAdB2c.cs#L18

The check should be && instead of || I think...

**Comment by rjygraham** [comment]
Closed. Thanks for catching this silly bug 👍
